services:
  app:
    image: yasindogac5959/bulletin-board-app:${BUILD_NUMBER}
    container_name: bulletin-board-app
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      APP_ENV: ${APP_ENV}
      APP_PORT: ${APP_PORT}
    restart: unless-stopped